version: '3.8'

services:
  transfer-order-pos:
    build: .
    container_name: transfer-order-pos
    ports:
      - "3000:3000"
    volumes:
      - ./tokens.json:/app/tokens.json
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s