openapi: 3.0.0
info:
  title: 'Composite Items'
  description: 'A form or version of an composite item that differs in some respect from other forms of the same or from a standard. You can create your composite items by associating multiple items and their respective quantities.'
  contact: {}
  version: 1.0.0
servers:
  -
    url: 'https://www.zohoapis.com/inventory/v1'
    description: 'API Endpoint'
tags:
  -
    name: compositeitems
    description: 'CompositeItems Module'
paths:
  /compositeitems:
    post:
      tags:
        - compositeitems
      summary: 'Creating a Composite Item'
      description: 'A new composite item can be created after creating items that we want to associcate with composite item. User can attach image for composite item by calling Different API ''https://www.zohoapis.com/inventory/v1/compositeitems/{composite_item_id}/image'', passing form-data parameter image i.e. -F image=bag_s.jpg'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.CREATE
    get:
      tags:
        - compositeitems
      summary: 'List All Composite Items'
      description: 'List of all composite items.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.READ
  '/compositeitems/{composite_item_id}':
    get:
      tags:
        - compositeitems
      summary: 'Retrieving a Composite Item'
      description: 'Retrieving details of an existing compostie item.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.READ
    put:
      tags:
        - compositeitems
      summary: 'Updating a composite item'
      description: 'Updating details of an existing composite item.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.UPDATE
    delete:
      tags:
        - compositeitems
      summary: 'Deleting a Composite Item'
      description: 'Deleting an existing Composite Item.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.DELETE
  '/compositeitems/{composite_item_id}/active':
    post:
      tags:
        - compositeitems
      summary: 'Mark as Active'
      description: 'Changing status of an existing composite item to active.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.CREATE
  '/compositeitems/{composite_item_id}/inactive':
    post:
      tags:
        - compositeitems
      summary: 'Mark as Inactive'
      description: 'Changing status of an existing composite item to inactive.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.CREATE
  /bundles:
    post:
      tags:
        - compositeitems
      summary: 'Create Assemblies'
      description: 'Assemblies is the technique of putting together different components in desired quantities to produce a single commodity. These components could be goods, services and other non-inventory items of your choice.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.CREATE
    get:
      tags:
        - compositeitems
      summary: 'Assemblies History'
      description: 'List of all Assemblies of a given composite item.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.READ
  '/bundles/{bundle_id}':
    get:
      tags:
        - compositeitems
      summary: 'Retrieve Assemblies'
      description: 'Fetches the details for an existing Assemblies.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.READ
    delete:
      tags:
        - compositeitems
      summary: 'Delete Assemblies'
      description: 'Deletes an existing Assemblies from Zoho Inventory.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.compositeitems.DELETE
components:
  securitySchemes:
    Zoho_Auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth'
          scopes:
            ZohoInventory.compositeitems.CREATE: 'Create Compositeitems'
            ZohoInventory.compositeitems.READ: 'Read Compositeitems'
            ZohoInventory.compositeitems.UPDATE: 'Update Compositeitems'
            ZohoInventory.compositeitems.DELETE: 'Delete Compositeitems'
