openapi: 3.0.0
info:
  title: Items
  description: 'An item is the product that is offered for sale. Nature of the product could be physical or digital. Based on the type of your business, you can offer one or more goods/services. Your product can be either fixed priced or a subscription service. Each of this may fall under a separate pricing category or have add ons associated to them.'
  contact: {}
  version: 1.0.0
servers:
  -
    url: 'https://www.zohoapis.com/inventory/v1'
    description: 'API Endpoint'
tags:
  -
    name: items
    description: 'Items Module'
paths:
  /items:
    post:
      tags:
        - items
      summary: 'Create an item'
      description: 'Creates a new item in Zoho Inventory.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.items.CREATE
    get:
      tags:
        - items
      summary: 'List all the items'
      description: 'Lists all the items present in Zoho Inventory.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.items.READ
  '/itemdetails':
    get:
      tags:
        - items
      summary: 'Bulk fetch item details'
      description: 'Fetch item details for the mentioned item IDs'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.items.READ
  '/items/{item_id}':
    get:
      tags:
        - items
      summary: 'Retrieve an item'
      description: 'Fetches the details for an existing item.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.items.READ
    put:
      tags:
        - items
      summary: 'Update an item'
      description: 'Update the details of an item.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.items.UPDATE
    delete:
      tags:
        - items
      summary: 'Delete an item'
      description: 'Deletes an existing item from Zoho Inventory.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.items.DELETE
  '/item/{item_id}/customfields':
    put:
      tags:
        - items
      summary: 'Update custom field in existing items'
      description: 'Update the value of the custom field in existing items.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.items.UPDATE
  '/items/{item_id}/image':
    delete:
      tags:
        - items
      summary: 'Delete an item image'
      description: 'Deletes the image associated for an item in Zoho Inventory.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.items.DELETE
  '/items/{item_id}/active':
    post:
      tags:
        - items
      summary: 'Mark as active'
      description: 'Changes the status of an item to active.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.items.CREATE
  '/items/{item_id}/inactive':
    post:
      tags:
        - items
      summary: 'Mark as inactive'
      description: 'Mark an item as inactive.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoInventory.items.CREATE
components:
  securitySchemes:
    Zoho_Auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth'
          scopes:
            ZohoInventory.items.CREATE: 'Create Items'
            ZohoInventory.items.READ: 'Read Items'
            ZohoInventory.items.UPDATE: 'Update Items'
            ZohoInventory.items.DELETE: 'Delete Items'
